### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by VSofficial** [VSofficial/airplane-ground-control#1]
<img width="403" alt="Screenshot 2023-03-06 at 9 50 44 PM" src="https://user-images.githubusercontent.com/39454933/223169174-6f62145e-bc21-469e-980b-531cec3aa269.png">

**Comment by VSofficial** [comment]
<img width="406" alt="Screenshot 2023-03-06 at 9 51 30 PM" src="https://user-images.githubusercontent.com/39454933/223169361-8493b857-1155-4739-a447-511ccfb965cc.png">

**Comment by adityagi02** [comment]
I'm starting with the login page.

**Comment by adityagi02** [comment]
#3 ✅ Login page.

**Comment by adityagi02** [comment]
i'll now work on **non-authentication** view.✈️

**Comment by adityagi02** [comment]
#4 & #6  ✅ This issue is **resolved**, you can close this now.
